"""Retrieval execution partition."""

from .indexing import (
    EmbeddingRecord,
    IndexCandidate,
    IndexCommitResult,
    InMemoryKeywordIndex,
    InMemoryVectorIndex,
    SparseTermsRecord,
    build_keyword_index,
    build_vector_index,
    commit_sparse_index,
    commit_vectors,
    extract_sparse_terms,
    extract_sparse_terms_for_chunks,
    generate_embedding,
    generate_embeddings,
    keyword_index_from_repository,
    run_keyword_search,
    run_vector_search,
    vector_index_from_repository,
)
from .execution import (
    AccessFilterResult,
    GraphTraversalResult,
    HybridSearchResult,
    apply_access_filter,
    merge_evidence_candidates,
    run_graph_retrieval,
    run_hybrid_search,
    run_keyword_retrieval,
    run_vector_retrieval,
)

PARTITION = "retrieval"

__all__ = [
    "PARTITION",
    "EmbeddingRecord",
    "IndexCandidate",
    "IndexCommitResult",
    "InMemoryKeywordIndex",
    "InMemoryVectorIndex",
    "SparseTermsRecord",
    "build_keyword_index",
    "build_vector_index",
    "commit_sparse_index",
    "commit_vectors",
    "extract_sparse_terms",
    "extract_sparse_terms_for_chunks",
    "generate_embedding",
    "generate_embeddings",
    "keyword_index_from_repository",
    "run_keyword_search",
    "run_vector_search",
    "vector_index_from_repository",
    "AccessFilterResult",
    "GraphTraversalResult",
    "HybridSearchResult",
    "apply_access_filter",
    "merge_evidence_candidates",
    "run_graph_retrieval",
    "run_hybrid_search",
    "run_keyword_retrieval",
    "run_vector_retrieval",
]
